import type { APIRoute } from 'astro'
import { getCollection } from 'astro:content'
import { canonical, abs } from '../lib/site'
import { categories, products, categoryHero } from '../lib/catalog'
import { infoPages } from '../data/pages'
import { legalPages } from '../data/legal'
import { allPlaces } from '../data/locations'

/**
 * The XML sitemap, at /sitemap.xml.
 *
 * Written here rather than generated by @astrojs/sitemap, which emits a
 * sitemap-index.xml pointing at a numbered chunk. At 486 indexable pages an
 * index is unnecessary — the limits are 50,000 URLs and 50MB — and a single
 * predictable /sitemap.xml is easier to submit and to check.
 *
 * Image entries live in this file too, so there is one sitemap rather than
 * two. @astrojs/sitemap could not do that: its SitemapItem type only carries
 * url, lastmod, changefreq, priority and links, and drops anything else.
 *
 * Anything noindex must be absent: /thank-you/, /search/ and /404.
 */
const esc = (s: string) =>
  s.replace(/[&<>"']/g, (c) =>
    ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;' })[c] as string
  )

interface Entry {
  path: string
  /** Homepage carries the most weight, then hubs, then leaf pages. */
  priority?: number
  images?: { url: string; title: string }[]
}

export const GET: APIRoute = async () => {
  const posts = await getCollection('blog')
  const guides = await getCollection('resources')

  const entries: Entry[] = [
    { path: '/', priority: 1.0 },

    ...categories.map((c) => {
      const hero = categoryHero(c.slug)?.images?.[0]
      return {
        path: `/${c.slug}`,
        priority: 0.8,
        images: hero ? [{ url: abs(`${hero.base}-1400.webp`), title: c.name }] : undefined,
      }
    }),

    ...products.map((p) => ({
      path: `/${p.slug}`,
      priority: 0.6,
      images: p.images.map((im) => ({ url: abs(`${im.base}-1400.webp`), title: p.name })),
    })),

    ...infoPages.filter((p) => !p.noindex).map((p) => ({ path: `/${p.slug}`, priority: 0.8 })),
    ...legalPages.map((p) => ({ path: `/${p.slug}`, priority: 0.3 })),

    { path: '/locations', priority: 0.8 },
    ...allPlaces.map((p) => ({ path: `/locations/${p.slug}`, priority: 0.6 })),

    { path: '/blog', priority: 0.8 },
    ...posts.map((p) => ({ path: `/blog/${p.id}`, priority: 0.6 })),

    { path: '/resources', priority: 0.8 },
    ...guides.map((g) => ({ path: `/resources/${g.id}`, priority: 0.6 })),

    { path: '/contact-us', priority: 0.8 },
    { path: '/request-a-quote', priority: 0.8 },
    { path: '/custom-packaging-tool', priority: 0.8 },
    { path: '/sitemap', priority: 0.3 },
  ]

  const lastmod = new Date().toISOString()

  const body = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
    '        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">',
    ...entries.map((e) =>
      [
        '  <url>',
        `    <loc>${esc(canonical(e.path))}</loc>`,
        `    <lastmod>${lastmod}</lastmod>`,
        '    <changefreq>weekly</changefreq>',
        `    <priority>${(e.priority ?? 0.6).toFixed(1)}</priority>`,
        ...(e.images ?? []).flatMap((i) => [
          '    <image:image>',
          `      <image:loc>${esc(i.url)}</image:loc>`,
          `      <image:title>${esc(i.title)}</image:title>`,
          '    </image:image>',
        ]),
        '  </url>',
      ].join('\n')
    ),
    '</urlset>',
    '',
  ].join('\n')

  return new Response(body, { headers: { 'Content-Type': 'application/xml; charset=utf-8' } })
}

export const prerender = true
